### ISSUE TITLE
Process id and Thread id missing from decoded LTTng logs

### ISSUE THREAD

**Issue by nibanks** [microsoft/CLOG#48]
The decoded logs currently look like the following:
```
[0][][04:09:46.599785][time][0x5623db075208] Updating Connection 0x7fd550000b20.
[0][][04:09:46.599786][time][0x5623db075208] Next Expiration = {1412964260, 0x7fd550000b20}.
[0][][04:09:46.599787][conn][0x7fd550000b20] Flush complete flags=0x0
[0][][04:09:46.599788][conn][0x7fd550000b20] Scheduling: 0
```
Notice the extra `[]` after the `[0]`.  This should be removed.

**Comment by ThadHouse** [comment]
This bug is located https://github.com/microsoft/CLOG/blob/master/src/clogutils/CLogConsoleTrace.cs#L106 and is actually 2 bugs

First is without a PID or TID, the brackets should not be printed
2nd is why are those not there.

**Comment by ThadHouse** [comment]
Turns out this is not actually a bug in anything CLOG is doing. PID and TID must be explicitly enabled, and this does not look like it can be done from the lttng headers clog itself generates. To add this, the following line must be added before lttng starts.

```
lttng add-context --userspace --type=vpid --type=vtid
```

I'm going to close this, as its not a clog issue. I have opened #68 to make CI builds have this extra context, and am working on updating msquic to fix this too.
